
export enum VoteOption {
    VOTE_OPTION_UNSPECIFIED = 0,
    VOTE_OPTION_YES = 1,
    VOTE_OPTION_ABSTAIN = 2,
    VOTE_OPTION_NO = 3,
    VOTE_OPTION_NO_WITH_VETO = 4
}

export enum ProposalStatus {
    PROPOSAL_STATUS_UNSPECIFIED = 0,
    PROPOSAL_STATUS_DEPOSIT_PERIOD = 1,
    PROPOSAL_STATUS_VOTING_PERIOD = 2,
    PROPOSAL_STATUS_PASSED = 3,
    PROPOSAL_STATUS_REJECTED = 4,
    PROPOSAL_STATUS_FAILED = 5
}

export enum Action {
    ACTION_UNSPECIFIED = 0,
    ACTION_VOTE = 1,
    ACTION_DELEGATE = 2,
    ACTION_EVM = 3,
    ACTION_IBC_TRANSFER = 4
}

export enum AuthorizationType {
    AUTHORIZATION_TYPE_UNSPECIFIED = 0,
    AUTHORIZATION_TYPE_DELEGATE = 1,
    AUTHORIZATION_TYPE_UNDELEGATE = 2,
    AUTHORIZATION_TYPE_REDELEGATE = 3
}

export enum BondStatus {
    BOND_STATUS_UNSPECIFIED = 0,
    BOND_STATUS_UNBONDED = 1,
    BOND_STATUS_UNBONDING = 2,
    BOND_STATUS_BONDED = 3
}
