
export enum VoteOption {
    VOTE_OPTION_UNSPECIFIED = 0,
    VOTE_OPTION_YES = 1, // 승인
    VOTE_OPTION_ABSTAIN = 2, // 기권
    VOTE_OPTION_NO = 3, // 거절
    VOTE_OPTION_NO_WITH_VETO = 4 // 거부권
}

export enum ProposalStatus {
    PROPOSAL_STATUS_UNSPECIFIED = 0,
    PROPOSAL_STATUS_DEPOSIT_PERIOD = 1, // 보증금 기간
    PROPOSAL_STATUS_VOTING_PERIOD = 2, // 투표 기간
    PROPOSAL_STATUS_PASSED = 3, // 통과
    PROPOSAL_STATUS_REJECTED = 4, // 거부
    PROPOSAL_STATUS_FAILED = 5 // 실패
}

export enum Action {
    ACTION_UNSPECIFIED = 0,
    ACTION_VOTE = 1,  // 투표
    ACTION_DELEGATE = 2, // 위임
    ACTION_EVM = 3,
    ACTION_IBC_TRANSFER = 4
}

export enum AuthorizationType {
    AUTHORIZATION_TYPE_UNSPECIFIED = 0,
    AUTHORIZATION_TYPE_DELEGATE = 1, // 위임
    AUTHORIZATION_TYPE_UNDELEGATE = 2, // 위임해제
    AUTHORIZATION_TYPE_REDELEGATE = 3 // 재위임
}

export enum BondStatus {
    BOND_STATUS_UNSPECIFIED = 0,
    BOND_STATUS_UNBONDED = 1,
    BOND_STATUS_UNBONDING = 2,
    BOND_STATUS_BONDED = 3
}
